finance_app/forms/expense_form.py
from flask_wtf import FlaskForm
from wtforms import (
    DateField,
    StringField,
    TextAreaField,
    DecimalField,
    SelectField,
    SubmitField,
)
from wtforms.validators import DataRequired


class ExpenseForm(FlaskForm):
    date = DateField("Date:", validators=[DataRequired()])
    title = StringField("Title:")
    notes = TextAreaField("Notes:")
    amount = DecimalField("Amount:", default=0, validators=[DataRequired()])
    category = SelectField("Category:")
    tags = StringField("Tags (seperate with semicolons):")

    submit = SubmitField("Submit")

finance_app/routes.py
import datetime
from flask import (
    Blueprint,
    current_app,
    redirect,
    render_template,
    send_file,
    url_for,
    request,
)
from sqlalchemy import exists
from finance_app.forms.expense_form import ExpenseForm
from finance_app.forms.income_form import IncomeForm
from finance_app.models import Category, Expense, ExpenseTag, Income, Tag
from finance_app import db
from finance_app.utils import int_to_money, make_csv_file
from flask_login import login_required
import calendar
from jinja2_fragments.flask import render_blocks

main = Blueprint("main", __name__, template_folder="templates")


@main.route("/")
@login_required
def index():
    return redirect(url_for("main.dashboard"))


@main.route("/list_categories")
@login_required
def list_categories():
    categories = Category.query.all()
    return render_template("list_categories.html", categories=categories)


@main.route("/dashboard")
@login_required
def dashboard():
    today = datetime.datetime.today()
    year = today.year
    months = [
        (month, (year if month <= today.month else year - 1)) for month in range(1, 13)
    ]
    months.sort(key=lambda x: x[1] * 100 + x[0], reverse=True)
    return render_template(
        "dashboard.html",
        categories=Category.query.all(),
        months=months,
        calendar=calendar,
    )


income = Blueprint(
    "income", __name__, url_prefix="/income", template_folder="templates"
)


@income.route("/list/")
@login_required
def list_income():
    page = request.args.get("page", 1, type=int)
    items_per_page = current_app.config.get("RESULTS_PER_PAGE") or 10

    query = Income.query

    # Apply category filter
    if category := request.args.get("category"):
        query = query.where(Income.category_code == category)

    # Apply title search filter
    if search_term := request.args.get("search"):
        query = query.where(Income.title.ilike(f"%{search_term}%"))

    income = query.order_by(
        Income.date.desc(),
        Income.create_date.desc(),
    ).paginate(page=page, per_page=items_per_page)

    next_url = None
    if income.has_next:
        next_url = url_for("income.list_income", page=income.next_num)

    if request.headers.get("HX-Request") == "true":
        return render_blocks(
            "list_income.html",
            ["income_rows", "load_more_btn"],
            income_items=income.items,
            next_url=next_url,
        )

    return render_template(
        "list_income.html",
        income_items=income.items,
        next_url=next_url,
    )


@income.route("/new", methods=["GET", "POST"])
@login_required
def new_income():
    form = IncomeForm()
    form.category.choices = [(c.code, c.title) for c in Category.query.all()]
    if form.validate_on_submit():
        total = int(form.amount.data * 100)
        income = Income(
            date=form.date.data,
            title=form.title.data,
            notes=form.notes.data,
            amount=total,
            category_code=form.category.data,
        )
        db.session.add(income)
        db.session.commit()

        return redirect(url_for("income.list_income"))
    return render_template("new_income.html", form=form)


@income.route("/new_paycheck", methods=["GET", "POST"])
@login_required
def new_paycheck():
    form: IncomeForm = IncomeForm()
    form.title.data = "Paycheck"
    form.category.choices = [(c.code, c.title) for c in Category.query.all()]
    form.category.data = "SPENDING"
    if form.validate_on_submit():
        total = int(form.amount.data * 100)
        adjusted_total = total + 35000 + 4384 + 10960
        god_amount = int(adjusted_total / 10)
        save_amount = int(total * 0.775)
        spend_amount = total - (god_amount + save_amount)

        db.session.add(
            Income(
                date=form.date.data,
                title=form.title.data,
                notes=form.notes.data,
                amount=god_amount,
                category_code="GOD",
            )
        )
        db.session.add(
            Income(
                date=form.date.data,
                title=form.title.data,
                notes=form.notes.data,
                amount=spend_amount,
                category_code="SPENDING",
            )
        )
        db.session.add(
            Income(
                date=form.date.data,
                title=form.title.data,
                notes=form.notes.data,
                amount=save_amount,
                category_code="SAVING",
            )
        )
        db.session.commit()

        return redirect(url_for("income.list_income"))
    return render_template("new_paycheck.html", form=form)


@income.route("/delete/<id>")
@login_required
def delete_income(id: int):
    income = Income.query.get_or_404(id)
    db.session.delete(income)
    db.session.commit()
    return redirect(url_for("income.list_income"))


@income.route("/export")
@login_required
def export_income():
    income: list[Income] = Income.query.all()
    if len(income) < 1:
        return "No income to download!"

    csv_rows = [
        {
            "Title": i.title,
            "Date": i.date.strftime("%m/%d/%Y"),
            "Amount": int_to_money(i.amount),
            "Category": i.category.title,
        }
        for i in income
    ]

    # Return file to user
    return send_file(
        make_csv_file(csv_rows),
        mimetype="text/csv",
        download_name="income.csv",
    )


expenses = Blueprint(
    "expenses",
    __name__,
    url_prefix="/expenses",
    template_folder="templates",
)


@expenses.route("/")
@login_required
def list_expenses():
    page = request.args.get("page", 1, type=int)
    items_per_page = current_app.config.get("RESULTS_PER_PAGE") or 10

    query = Expense.query

    # Apply tag search filter
    if tag := request.args.get("tag"):
        tag = Tag.query.where(Tag.name == tag).first()
        query = query.where(
            exists().where(ExpenseTag.tag == tag, ExpenseTag.expense_id == Expense.id)
        )

    # Apply category filter
    if category := request.args.get("category"):
        query = query.where(Expense.category_code == category)

    # Apply title search filter
    if search_term := request.args.get("search"):
        query = query.where(Expense.title.ilike(f"%{search_term}%"))

    # Paginate results
    expenses = query.order_by(
        Expense.date.desc(),
        Expense.create_date.desc(),
    ).paginate(page=page, per_page=items_per_page)

    args = request.args.copy()
    if "page" in args:
        args.pop("page")

    next_url = None
    if expenses.has_next:
        next_url = url_for(
            "expenses.list_expenses",
            page=expenses.next_num,
            **args,
        )

    if request.headers.get("HX-Request") == "true":
        return render_blocks(
            "list_expenses.html",
            ["expense_rows", "load_more_btn"],
            expenses=expenses.items,
            next_url=next_url,
        )

    return render_template(
        "list_expenses.html",
        expenses=expenses.items,
        next_url=next_url,
    )


@expenses.route("/search/data", methods=["GET", "POST"])
@login_required
def get_expense_data_by_title():
    title = request.args.get("title")
    expense: Expense = (
        Expense.query.filter_by(title=title).order_by(Expense.date.desc()).first()
    )
    if expense:
        data = {
            "date": expense.date.strftime("%Y-%m-%d"),
            "notes": expense.notes,
            "amount": expense.amount / 100,
            "category": expense.category_code,
            "tags": ";".join(set([et.tag.name for et in expense.tags])),
        }
        return data, 200
    return {"error": "No expenses with this title found."}, 404


@expenses.route("/new", methods=["GET", "POST"])
@login_required
def new_expense():
    form: ExpenseForm = ExpenseForm()
    form.category.choices = [(cat.code, cat.title) for cat in Category.query.all()]
    # Default the date field to the same date as the most recently create expense
    if request.method == "GET":
        most_recent: Expense = Expense.query.order_by(
            Expense.create_date.desc()
        ).first()
        form.date.data = most_recent.date
    # Validate the form
    if form.validate_on_submit():
        category = Category.query.get(form.category.data)
        expense = Expense(
            date=form.date.data,
            title=form.title.data,
            notes=form.notes.data,
            amount=int(form.amount.data * 100),
            category=category,
        )
        db.session.add(expense)
        # Process tags
        if form.tags.data:
            for tag in form.tags.data.split(";"):
                tag = Tag.query.where(Tag.name == tag).first() or Tag(name=tag)
                db.session.add(ExpenseTag(tag=tag, expense=expense))

        db.session.commit()

        return redirect(url_for("expenses.list_expenses"))
    return render_template("expense_form_new.html", form=form)


@expenses.route("/expenses/<id>", methods=["GET", "POST"])
@login_required
def expense(id: int):
    """Update an existing expense."""
    expense: Expense = Expense.query.get_or_404(id)
    form: ExpenseForm = ExpenseForm()
    form.category.choices = [(cat.code, cat.title) for cat in Category.query.all()]
    if request.method == "GET":
        form.amount.data = expense.amount / 100
        form.notes.data = expense.notes
        form.date.data = expense.date
        form.title.data = expense.title
        form.category.data = expense.category_code
        form.tags.data = expense.tag_string()

    elif form.validate_on_submit():
        category = Category.query.get(form.category.data)
        expense.date = form.date.data
        expense.title = form.title.data
        expense.notes = form.notes.data
        expense.amount = int(form.amount.data * 100)
        expense.category = category

        if form.tags.data:
            for tag in expense.tags:

finance_app/templates/category_header.html
<th scope="row" style="background-color: #{{category.color}}">
    {{ category.title }}:
</th>

finance_app/templates/dashboard.html
{% extends "layout.html" %}

{% block content %}


<h2>Category Balances:</h2>
<table class="table">
    {% for category in categories %}
    <tr>
        {% include 'category_header.html' %}

        {% set balance = category.balance_current() %}
        <td scope="row" style="
        {% if balance >= 0 %}
        background-color: #C6EFCE;
        color: #006100;
        {% else %}
        background-color: #FFC7CE;
        color: #9C0006;
        {% endif %}
        ">
            {{ balance | int_to_money }}
        </td>
        <td class="text-end w-25">
            <a href="{{url_for('expenses.list_expenses', category=category.code)}}"
                class="text-reset">
                Expenses
            </a> |
            <a href="{{url_for('income.list_income', category=category.code)}}"
                class="text-reset">
                Income
            </a>
        </td>
    </tr>
    {% endfor %}
</table>


<h2>Monthly Balances</h2>
<table class="table">
    <tr>
        <th>Month</th>
        {% for category in categories %}
        <th style="background-color: #{{category.color}}">
            {{ category.title }}:
        </th>
        {% endfor %}
    </tr>
    {% for month_year in months %}
    {% set month = month_year[0] %}
    {% set year = month_year[1] %}
    <tr>
        <td>
            {{calendar.month_name[month]}} {{ year }}
        </td>
        {% for category in categories %}
        {% set balance = category.balance_for_month(year, month)%}
        <td scope="row" style="background-color: #{{category.color}}">
            {{ balance | int_to_money }}
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>

{% endblock %}

finance_app/templates/expense_form.html
{% extends "layout.html" %}
{% block content %}
<h1>{{heading or "Add Expense"}}</h1>
<form method="post" novalidate>
    {{ form.hidden_tag() }}

    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <ul>
            {% for field, errors in form.errors.items() %}
            {% for error in errors %}
            <li><b>{{ form[field].label.text }}:</b> {{ error }}</li>
            {% endfor %}
            {% endfor %}
        </ul>
    </div>
    {% else %}
    {% endif %}

    <div class="mb-2">
        {{ form.date.label }}<br>
        {{ form.date(class="form-control", autofocus=True)}}
    </div>
    <div class="mb-2">
        {{ form.title.label }}<br>
        {{ form.title(class="form-control") }}
    </div>
    <div class="mb-2">
        {{ form.amount.label }}<br>
        {{ form.amount(class="form-control") }}
    </div>
    <div class="mb-2">
        {{ form.category.label }}<br>
        {{ form.category(class="form-control") }}
    </div>
    <div class="mb-2">
        {{ form.tags.label }}<br>
        {{ form.tags(class="form-control") }}
    </div>
    <p>{{ form.submit(class="btn btn-primary mt-3") }}</p>
    <div class="mb-2">
        {{ form.notes.label }}<br>
        {{ form.notes(class="form-control") }}
    </div>
</form>
{% endblock %}

finance_app/templates/expense_form_edit.html
{% extends "layout.html" %}
{% block content %}
<h1>Edit Expense</h1>
<form method="post" novalidate>
    {{ form.hidden_tag() }}

    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <ul>
            {% for field, errors in form.errors.items() %}
            {% for error in errors %}
            <li><b>{{ form[field].label.text }}:</b> {{ error }}</li>
            {% endfor %}
            {% endfor %}
        </ul>
    </div>
    {% else %}
    {% endif %}

    <div class="mb-2">
        {{ form.date.label }}<br>
        {{ form.date(class="form-control", autofocus=True)}}
    </div>
    <div class="mb-2">
        {{ form.title.label }}<br>
        {{ form.title(class="form-control") }}
    </div>
    <div class="mb-2">
        {{ form.amount.label }}<br>
        {{ form.amount(class="form-control") }}
    </div>
    <div class="mb-2">
        {{ form.category.label }}<br>
        {{ form.category(class="form-control") }}
    </div>
    <div class="mb-2">
        {{ form.tags.label }}<br>
        {{ form.tags(class="form-control") }}
    </div>
    <p>{{ form.submit(class="btn btn-primary mt-3") }}</p>
    <div class="mb-2">
        {{ form.notes.label }}<br>
        {{ form.notes(class="form-control") }}
    </div>
</form>
{% endblock %}

finance_app/templates/expense_form_new.html
{% extends "layout.html" %}
{% block content %}
<h1>Add Expense</h1>
<form method="post" novalidate>
    {{ form.hidden_tag() }}

    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <ul>
            {% for field, errors in form.errors.items() %}
            {% for error in errors %}
            <li><b>{{ form[field].label.text }}:</b> {{ error }}</li>
            {% endfor %}
            {% endfor %}
        </ul>
    </div>
    {% else %}
    {% endif %}

    <div class="mb-2">
        {{ form.date.label }}<br>
        {{ form.date(class="form-control", autofocus=True)}}
    </div>
    <div class="mb-2">
        {{ form.title.label }}<br>
        <div class="input-group">
            {{ form.title(class="form-control") }}
            <script>
                function autoFill() {
                    const titleInput = document.getElementById("title");
                    fetch("/expenses/search/data?title=" + titleInput.value)
                        .then((response) => response.json())
                        .then((data) => {
                            if (data.amount) {
                                document.getElementById("amount").value = data.amount;
                            }
                            if (data.tags) {
                                document.getElementById("tags").value = data.tags;
                            }
                            if (data.category) {
                                const categorySelect = document.getElementById("category")
                                categorySelect.childNodes.forEach((option) => {
                                    if (option.value == data.category) {
                                        option.selected = true;
                                    } else {
                                        option.selected = false;
                                    }
                                });
                            }
                        })
                        .catch((error) => {
                            console.error("Error fetching data:", error);
                        });
                }
            </script>
            <button class="btn btn-primary" onclick="autoFill()" type="button">
                Auto-Fill
            </button>
        </div>
    </div>
    <div class="mb-2">
        {{ form.amount.label }}<br>
        {{ form.amount(class="form-control") }}
    </div>
    <div class="mb-2">
        {{ form.category.label }}<br>
        {{ form.category(class="form-control") }}
    </div>
    <div class="mb-2">
        {{ form.tags.label }}<br>
        {{ form.tags(class="form-control") }}
    </div>
    <p>{{ form.submit(class="btn btn-primary mt-3") }}</p>
    <div class="mb-2">
        {{ form.notes.label }}<br>
        {{ form.notes(class="form-control") }}
    </div>
</form>
{% endblock %}

finance_app/templates/index.html
{% extends "layout.html" %}

{% block content %}
Hello world!
{% endblock %}

finance_app/templates/layout.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Finance App{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link rel="icon" href="{{ url_for('static', filename='money.png')}}">
        <script src="{{url_for('static', filename='htmx.js')}}"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                    <ul class="navbar-nav hstack gap-3">
                        <li class="nav-item">
                        <a href="{{url_for("main.dashboard")}}">
                            Dashboard
                        </a>
                        </li>
                        <li class="nav-item">
                        <a href="{{url_for("expenses.list_expenses")}}">
                            Expenses
                        </a>
                        </li>
                        <li class="nav-item">
                        <a href="{{url_for("income.list_income")}}">
                            Income
                        </a>
                        </li>
                    </ul>
                </div>
            </div> 
        </nav>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

finance_app/templates/list_categories.html
<table>
    <tr>
        <th>Code</th>
        <th>Title</th>
    </tr>
    {% for cat in categories %} 
        <tr>
            <td>{{ cat.code }}</td>
            <td>{{ cat.title }}</td>
        </tr>
    {% endfor %}
</table>

finance_app/templates/list_expenses.html
{% extends "layout.html" %}
{% block content %}
<div class="d-flex flex-row justify-content-between mb-3">
    <form method="GET" class="me-2">
        <input class="form-control" type="search" name="search" id="search"
            placeholder="Search" />
    </form>
    <div class="btn-group">
        <a class="btn btn-secondary" href="{{url_for('expenses.export_expenses')}}">
            Export
        </a>
        <a autofocus class="btn btn-primary" href="{{url_for('expenses.new_expense')}}">
            New Expense
        </a>
    </div>
</div>
<div class="table-responsive">


    <table class="table">
        <tr>
            <th scope="col">Date</th>
            <th scope="col" class="text-center">Title</th>
            <th scope="col" class="text-center">Amount</th>
            <th scope="col" class="text-center">Category</th>
            <th scope="col" class="text-center">Tags</th>
            <th>Actions</th>
        </tr>

        <tbody id="table_body">
            {% block expense_rows %}
            {% for expense in expenses %}
            <tr>
                <td>{{ expense.date.strftime('%m/%d/%y') }}</td>
                <td class="text-center">
                    <a href="{{url_for('expenses.expense', id=expense.id)}}">
                        {{ expense.title }}
                    </a>
                </td>
                <td class="text-center">{{ expense.formatted_amount() }}</td>
                <td class="text-center" style="background: #{{expense.category.color}}">
                    <a class="text-decoration-none text-reset"
                        href="{{url_for('expenses.list_expenses', category=expense.category.code)}}">
                        {{ expense.category.title }}
                    </a>
                </td>
                <td class="text-center">
                    {% for expense_tag in expense.tags %}
                    <span class="badge"
                        style="background-color: #{{ expense_tag.tag.color }};">
                        <a href="{{url_for('expenses.list_expenses', tag=expense_tag.tag.name)}}"
                            class="text-white text-decoration-none">
                            {{ expense_tag.tag.name }}
                        </a>
                    </span>
                    {% endfor %}
                </td>
                <td>
                    <a href='{{url_for("expenses.delete_expense", id=expense.id)}}'
                        style="text-decoration: none;">
                        <img src="{{ url_for('static', filename='delete.svg') }}"
                            alt="Delete" title="Delete" />
                    </a>
                    <a href='{{url_for("expenses.repeat_expense", id=expense.id)}}'>
                        <img src="{{ url_for('static', filename='repeat.svg') }}"
                            alt="Repeat" title="Repeat" />
                    </a>
                </td>

            </tr>
            {% endfor %}
        </tbody>
        {% endblock %}

    </table>
</div>
{% block load_more_btn %}
<div id="load_more_btn_wrapper" hx-swap-oob="true" class="w-100">
    {% if next_url %}
    <a class="btn btn-primary w-100 mb-3" href="{{next_url}}" hx-get="{{next_url}}"
        hx-target="#table_body" hx-swap="beforeend">
        Load More
    </a>
    {% else %}
    <p class="text-center mb-3 fst-italic">
        You have reached the end of the list!
    </p>
    {% endif %}
</div>
{% endblock load_more_btn %}
{% endblock %}

finance_app/templates/login.html
{% extends "layout.html" %}
{% block content %}
<form method="post">
    <label for="password" class="form-label">
        Password:
    </label>
    <input id="password" name="password" class="form-control" type="password">
    </input>
</form>
{% endblock %}

finance_app/templates/new_expense.html
{% extends "layout.html" %}
{% block content %}
<h1>Add Expense</h1>
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <div>
        {{ form.date.label }}<br>
        {{ form.date(class="form-control", autofocus=True)}}
    </div>
    <div>
        {{ form.title.label }}<br>
        {{ form.title(class="form-control") }}
    </div>
    <div>
        {{ form.amount.label }}<br>
        {{ form.amount(class="form-control") }}
    </div>
    <div>
        {{ form.category.label }}<br>
        {{ form.category(class="form-control") }}
    </div>
    <p>{{ form.submit(class="btn btn-primary mt-3") }}</p>
    <div>
        {{ form.notes.label }}<br>
        {{ form.notes(class="form-control") }}
    </div>
</form>
{% endblock %}

finance_app/templates/new_income_categories.html
{% extends "layout.html" %}
{% block content %}
{% for form in form.categories %}
    {{ form.hidden_tag() }}
    {# Flask-WTF needs `hidden_tag()` so CSRF works for each form #}
    <div>
        {{ form.percentage.label }}
        {{ form.percentage(class="form-control") }}
    </div>
{% endfor %}
{% endblock %}

finance_app/templates/new_paycheck.html
{% extends "layout.html" %}
{% block content %}
<h1>Add Paycheck</h1>
<form method="post" >
    {{ form.hidden_tag() }}
    <div>
        {{ form.title.label }}<br>
        {{ form.title(class="form-control",disabled=true) }}
    </div>
    <div>
        {{ form.date.label }}<br>
        {{ form.date(class="form-control")}}
    </div>
    <div>
        {{ form.amount.label }}<br>
        {{ form.amount(class="form-control") }}
    </div>
    <div>
        {{ form.notes.label }}<br>
        {{ form.notes(class="form-control") }}
    </div>
    <p>{{ form.submit(class="btn btn-primary mt-3") }}</p>
</form>
{% endblock %}

finance_app/templates/view_expense.html
{% extends "layout.html" %}

<div>
    <h1>{{expense.title}}</h1>
</div>